# Generated by Django 6.0.1 on 2026-02-10 11:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('release_year', models.PositiveIntegerField(verbose_name='Год выпуска')),
                ('category', models.CharField(choices=[('MOVIE', 'Фильм'), ('GAME', 'Игра'), ('SERIES', 'Сериал')], default='MOVIE', max_length=10, verbose_name='Категория')),
                ('poster', models.ImageField(blank=True, upload_to='posters/')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL Slug')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название жанра')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main_pages.content')),
                ('developer', models.CharField(max_length=100, verbose_name=' Разработчики')),
                ('publisher', models.CharField(max_length=100, verbose_name=' Издатель')),
                ('system_requirements', models.TextField(blank=True, verbose_name=' Системные требования')),
            ],
            bases=('main_pages.content',),
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main_pages.content')),
                ('director', models.CharField(max_length=100, verbose_name='Режиссер')),
                ('actors', models.TextField(blank=True, verbose_name='Актеры')),
                ('duration', models.PositiveIntegerField(verbose_name='Длительность')),
            ],
            bases=('main_pages.content',),
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main_pages.content')),
                ('seasons_count', models.PositiveIntegerField(verbose_name='Количество сезонов')),
                ('status', models.CharField(choices=[('ONGOING', 'Выходит'), ('ENDED', 'Завершен'), ('CANCELED', 'Закрыт'), ('PAUSED', 'Приостановлен'), ('ANNOUNCED', 'Анонс')], default='ONGOING', max_length=15, verbose_name='Статус производства')),
                ('director', models.CharField(max_length=100, verbose_name='Режиссер')),
                ('actors', models.TextField(blank=True, verbose_name='Актеры')),
            ],
            bases=('main_pages.content',),
        ),
        migrations.AddField(
            model_name='content',
            name='genres',
            field=models.ManyToManyField(related_name='contents', to='main_pages.genre', verbose_name='Жанры'),
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='scrins/')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrins', to='main_pages.content')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Оценка')),
                ('review', models.TextField(blank=True, verbose_name='Отзыв')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='main_pages.content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтинги',
                'unique_together': {('user', 'content')},
            },
        ),
    ]
