# Generated by Django 6.0.1 on 2026-03-03 14:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_pages', '0004_alter_rating_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={},
        ),
        migrations.AddField(
            model_name='rating',
            name='status',
            field=models.CharField(choices=[('WATCHED', 'Просмотрено'), ('PLANNING', 'В планах'), ('FAVORITE', 'Любимое')], default='WATCHED', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Оценка'),
        ),
    ]
