# Generated by Django 6.0.1 on 2026-03-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_pages', '0005_alter_rating_options_rating_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='review',
            field=models.TextField(blank=True, null=True, verbose_name='Отзыв'),
        ),
    ]
